---
---


# params
```{r}
infile = "/mnt/local/GEM_to_CellRanger/data/data-full.gem"
outdir = "/mnt/local/discovery/bgi"
bin_size = 100
project_name = "tongue4bin100"

set.seed(3)

outdir <- file.path(outdir, project_name)
```


# LoadBGI_Spatial FN
```{r}
save_rds = T
pro_name = "Spatial"
UMI_GreyScale_Image = T
assay = "Spatial"
slice = "slice1"
```

```{r}
# read in data
dat <- data.table::fread(file = infile)
colnames(dat)[1:4] <- c("geneID", "x", "y", "UMICount")
rowname_style <- "BIN"

# truncate coords to bin start (bin_size + 1)
dat$x <- trunc((dat$x - min(dat$x)) / bin_size + 1)
dat$y <- trunc((dat$y - min(dat$y)) / bin_size + 1)

# bin counts
if ("MIDCounts" %in% colnames(dat)) {
    dat <- dat[, sum(MIDCounts), by = .(geneID, x, y)]
} else if ("MIDCount" %in% colnames(dat)) {
  dat <- dat[, sum(MIDCount), by = .(geneID, x, y)]	
} else {
    dat <- dat[, sum(UMICount), by = .(geneID, x, y)]
}

# ids
dat$bin_ID <- max(dat$x) * (dat$y - 1) + dat$x
bin.coor <- dat[, sum(V1), by = .(x, y)]
```

# greyscale image
there are missing data lines (both x and y), as visible in the bin=1 image
```{r}
if (UMI_GreyScale_Image) {
        scale_grey <- bin.coor$V1 / quantile(bin.coor$V1, probs = 0.95)
        scale_grey[scale_grey > 1] <- 1
        tissue_lowres_image <- as.matrix(Matrix::sparseMatrix(
        i = bin.coor$y,
        j = bin.coor$x,
        x = scale_grey
        ))
        tissue_lowres_image_r <- raster::raster(tissue_lowres_image)
        tissue_lowres_image_r <- raster::writeRaster(tissue_lowres_image_r, file.path(outdir, paste0(pro_name, "_UMIGreyScaleFakeIMG.tiff")), overwrite=T)
    } else tissue_lowres_image <- matrix(0, max(bin.coor$y), max(bin.coor$x))
```

```{r}
temp <- as.matrix(Matrix::sparseMatrix(
  i = bin.coor$y,
  j = bin.coor$x,
  x = bin.coor$V1
))
```

# creating a basic seurat obj containing genes, bin_ids and counts
```{r}
geneID <- seq(length(unique(dat$geneID)))
hash.G <- data.frame(row.names = unique(dat$geneID), values = geneID)
gen <- hash.G[dat$geneID, "values"]

bin_ID <- unique(dat$bin_ID)
hash.B <- data.frame(row.names = sprintf("%d", bin_ID), values = bin_ID)
bin <- hash.B[sprintf("%d", dat$bin_ID), "values"]

cnt <- dat$V1
mat <- Matrix::sparseMatrix(i = gen, j = bin, x = cnt)
rownames(mat) <- rownames(hash.G)
colnames(mat) <- paste(rowname_style, sprintf("%d", seq(max(hash.B[, "values"]))), sep = ".")
object <- Seurat::CreateSeuratObject(mat, project = assay, assay = assay)
rm(dat)
gc()
```


```{r}
generate_spatialObj <- function(image, scale.factors, tissue.positions, filter.matrix = TRUE) {
  if (filter.matrix) {
      tissue.positions <- tissue.positions[which(tissue.positions$tissue == 1), , drop = FALSE]
  }
  unnormalized.radius <- scale.factors$fiducial_diameter_fullres * scale.factors$tissue_lowres_scalef
  spot.radius <- unnormalized.radius / max(dim(image))
  return(new(Class = "VisiumV1",
              image = image,
              scale.factors = Seurat::scalefactors(
                  spot = scale.factors$tissue_hires_scalef,
                  fiducial = scale.factors$fiducial_diameter_fullres,
                  hires = scale.factors$tissue_hires_scalef,
                  lowres = scale.factors$tissue_lowres_scalef
              ),
              coordinates = tissue.positions,
              spot.radius = spot.radius
          ))
}
```

### DF of bin coords to pixel coords
```{r}
tissue_positions_list <- data.frame(
    row.names = paste(rowname_style, rownames(hash.B), sep = "."), # bin ids
    tissue = 1,
    row = bin.coor$y, col = bin.coor$x, # repeated - bin coord = image coords
    imagerow = bin.coor$y, imagecol = bin.coor$x
)
```

### scalefactors json - apparently required
```{r}
    scalefactors_json <- rjson::toJSON(list(
        fiducial_diameter_fullres = 1,
        tissue_hires_scalef = 1,
        tissue_lowres_scalef = 1
    ))

```


```{r}
    spatialObj <- generate_spatialObj(
        image = tissue_lowres_image,
        scale.factors = rjson::fromJSON(scalefactors_json), #WHY!!
        tissue.positions = tissue_positions_list
    )

```

```{r}
spatialObj <- spatialObj[Seurat::Cells(spatialObj)]
    Seurat::DefaultAssay(spatialObj) <- assay
    #spatialObj[slice] <- spatialObj

    spatialObj <- subset(spatialObj, subset = nCount_Spatial > 0)
```


